name: 'Setup Nodejs'
description: 'Steps to setup Nodejs, install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install
      shell: bash
