name: CI

on:
  pull_request:
    branches: "*"

  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nodejs
        uses: ./.github/actions/node-setup

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test
